In [1]:
import numpy as np
import pandas as pd

In [2]:
file = "diabetes_data.csv"
dataset = pd.read_csv(file)
dataset.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6    148.0         72       35      0.0  33.6  0.627   50   
1            1     85.0         66       29      0.0  26.6  0.351   31   
2            8    183.0         64        0      0.0  23.3  0.672   32   
3            1     89.0         66       23     94.0  28.1  0.167   21   
4            0    137.0         40       35    168.0  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [5]:
pd.isnull(dataset).sum()

pregnancies    0
glucose        1
diastolic      0
triceps        0
insulin        1
bmi            1
dpf            1
age            0
diabetes       0
dtype: int64

In [9]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
X = imputer.fit_transform(X[:,:])
X[:5]


array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01]])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:,:])
X_test[:,:] = sc.fit_transform(X_test[:,:])

In [15]:
X_test

array([[-0.89295432,  2.39507259,  0.39763774, ...,  1.52657475,
         2.78935129, -0.93064283],
       [-0.56553774, -0.42589245,  0.2898275 , ...,  0.31944116,
        -0.27698825, -0.83598035],
       [ 0.08929543, -1.37643502, -0.35703388, ...,  0.37136088,
        -0.31725331, -0.64665539],
       ...,
       [ 0.08929543,  0.64730077,  0.93668889, ...,  1.66935399,
         0.4694641 , -0.93064283],
       [-0.23812115, -0.14992848,  0.2898275 , ..., -0.62809381,
        -1.19689011, -0.74131787],
       [-0.89295432, -0.42589245,  0.18201727, ..., -0.04399691,
         1.01459113, -0.74131787]])

In [16]:
X_train

array([[ 0.90832902,  0.91580498,  0.44912368, ...,  0.37769299,
         0.67963389,  1.69955804],
       [ 0.03644676, -0.75171657, -0.47230103, ..., -0.50777213,
        -0.06890971, -0.96569189],
       [-1.12606292,  1.38774504,  1.06340683, ...,  2.54075778,
        -0.1170089 , -0.88240283],
       ...,
       [ 0.03644676, -0.84610458, -0.21634972, ..., -0.95050469,
        -0.95573848, -1.04898095],
       [ 2.0708387 , -1.12926862,  0.24436264, ..., -0.2674316 ,
        -0.4987962 ,  0.11706589],
       [ 0.32707418,  0.47532759,  0.65388473, ..., -4.07493161,
         0.52331153,  2.94889395]])