In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
file = "winequality-red.csv"
dataset = pd.read_csv(file)
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
pd.isnull(dataset).sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [4]:
dataset["quality"].unique()

array([5, 6, 7, 4, 8, 3])

In [12]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:,:])
X_test[:,:] = sc.fit_transform(X_test[:,:])

In [18]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train,y_train)

SVC()

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_train = confusion_matrix(y_train, classifier.predict(X_train))
print(cm_train)
print(accuracy_score(y_train, classifier.predict(X_train))*100)

[[  0   0   8   0   0   0]
 [  0   1  31   9   1   0]
 [  0   0 439 105   2   0]
 [  0   0 133 346  17   0]
 [  0   0  10  95  67   0]
 [  0   0   0  10   5   0]]
66.69272869429241


In [21]:
y_pred = classifier.predict(X_test)
comp = pd.DataFrame(np.concatenate((y_test.reshape(len(y_test),1),
                                    y_pred.reshape(len(y_pred),1)),
                                    1),
                                   columns=["actual","predicted"])
comp

actual  predicted
0         6          5
1         5          5
2         7          7
3         6          5
4         5          6
..      ...        ...
315       6          6
316       4          6
317       5          6
318       4          5
319       6          6

[320 rows x 2 columns]

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_test = confusion_matrix(y_test, y_pred)
print(cm_test)
print(accuracy_score(y_test, y_pred)*100)

[[  0   0   1   1   0   0]
 [  0   0   8   3   0   0]
 [  0   0 102  32   1   0]
 [  0   0  40  96   6   0]
 [  0   0   1  17   9   0]
 [  0   0   0   1   2   0]]
64.6875
