### KNN 
Aim: Download the famous dataset of iris and Implement KNN algorithm to predict the class
to which these plants belong, Calculate the performance matric and compare the error
rate with K value

#### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing the data set 

In [ ]:
file = "Iris.csv"
dataset = pd.read_csv(file)
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
pd.isnull(dataset).sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

There are no missing values in the data set.

In [ ]:
dataset["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

The features can be classified into the 3 categories.

In [ ]:
dataset= dataset.drop(columns =["Id"], axis=1)
dataset

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

We don't need Id column, hence we drop that column

#### Polarizing the feature columns and dependent variable column.

In [ ]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print("X=",X[:10])
print("y=",y[:10])

X= [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
y= ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


#### In this data set we don't have categorical features. So, Encoding is not required for features.
#### Rather we require label encoding for dependent variable. 

In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y = label.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

We have successfully encoded our dependent feature.

#### Splitting the data set into Training set and Test 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=0)

#### As our data set consists of continuous variable, we need to scale our features.
#### Feature Scaling (Standardization)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:,:])
X_test[:,:] = sc.fit_transform(X_test[:,:])

We can see that our features have been scaled using Standardization

#### Training KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

#### Predicting Train results
Confusion Matrix and accuracy of train set

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_train = confusion_matrix(y_train, classifier.predict(X_train) )
print("Confusion Matrix: \n",cm_train)
print("Train accuracy: ", 
      accuracy_score(y_train, 
                     classifier.predict(X_train))*100,"%")

Confusion Matrix: 
 [[39  0  0]
 [ 0 35  2]
 [ 0  2 42]]
Train accuracy:  96.66666666666667 %


#### Predicting Test results

In [ ]:
y_pred = classifier.predict(X_test)
comparison = pd.DataFrame(np.concatenate((y_test.reshape(len(y_test),1), 
                                          y_pred.reshape(len(y_pred),1)),
                                          1), 
                          columns=["Actual","Predicted"])
comparison[:10]

Actual  Predicted
0       2          2
1       1          1
2       0          0
3       2          2
4       0          0
5       2          2
6       0          0
7       1          2
8       1          2
9       1          1

Confusion Matrix and accuracy of test set

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_test = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n",cm_test)
print("Test accuracy: ", accuracy_score(y_test, y_pred)*100,"%")

Confusion Matrix: 
 [[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]
Test accuracy:  83.33333333333334 %


#### Performance Metrics 

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.62      0.76        13
           2       0.55      1.00      0.71         6

    accuracy                           0.83        30
   macro avg       0.85      0.87      0.82        30
weighted avg       0.91      0.83      0.84        30



### Conclusion: Thus we have successfully completed the implementation of KNN Classifier.